activity_feature_groups {
  features {
        feature_name: "product_id"
        feature_type: STRING
        vocab_size: 3952
        embedding_dim: 8
        feature_length: 5
      }
      features {
        feature_name: "user_id"
        feature_type: STRING
        feature_length: 5
      }
      features {
        feature_name: "timestamp"
        feature_type: STRING
        feature_length: 5
      }
  encoder_type: CNN
}
